version: '3.7'
services:
  nginx:
    image: nginx
    ports:    
      - 5433:5432
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client.key:/etc/nginx/client.key
      - ./client.crt:/etc/nginx/client.crt
      - ./ca.crt:/etc/nginx/ca.crt
      - ./server.crt:/etc/nginx/server.crt
