version: '3.7'
services:
  nginx:
    image: nginx
    ports:
   
      - 8012:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.key:/etc/nginx/server.key
      - ./server.crt:/etc/nginx/server.crt
      - ./ca.crt:/etc/nginx/ca.crt
      - ./client.crt:/etc/nginx/client.crt
